### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Tswings** [LCS2-IIITD/DABERTA-EMNLP-2022#1]
Good paper. May I ask when this dataset will be released?

**Comment by ary1733** [comment]
Hi @meghasundriyal, I am trying to implement this paper. Can you guide me where can I find the dataset?

**Comment by meghasundriyal** [comment]
You may find the data files here: https://drive.google.com/drive/folders/1jRfE6U7zLxLXQUweWd3dsq4sIGppQG74
